a, b = input().split(" ")
a = int(a)
b = int(b)
sum = int(a + b)
dif = int(a - b)
mul = int(a * b)
div = int(a / b)
na = int(a % b)

print(sum)
print(dif)
print(mul)
print(div)
print(na)
print(format(a / b, '.2f'))